name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install dependencies
        run: shards install

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo (d4-format)
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: d4-format
          cache-targets: true

      - name: Clone d4-format / d4binding repository
        run: |
          git clone --depth 1 https://github.com/38/d4-format.git
          cd d4-format
          cargo build --release --package=d4binding
          ls -la target/release/

      - name: Verify library installation
        run: |
          echo "Checking library files..."
          find d4-format/target/release -name "*d4binding*" -type f
          echo "Library path: $LD_LIBRARY_PATH"

      - name: Run Crystal tests
        run: |
          sudo apt install libgc-dev # Workaround
          crystal spec --link-flags="-L$PWD/d4-format/target/release -Wl,-rpath,$PWD/d4-format/target/release"
