name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install dependencies
        run: shards install

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Clone d4-format / d4binding repository
        run: |
          git clone https://github.com/38/d4-format.git
          cd d4-format
          cargo build --release --package=d4binding
          ls -la target/release/
          echo "LD_LIBRARY_PATH=$PWD/d4-format/target/release:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$PWD/d4-format/target/release:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$PWD/d4-format/target/release:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Verify library installation
        run: |
          echo "Checking library files..."
          find d4-format/target/release -name "*d4binding*" -type f
          echo "Library path: $LD_LIBRARY_PATH"

      - name: Run Crystal tests
        run: |
          echo "Running Crystal tests..."
          crystal spec
          echo "Tests completed"
        continue-on-error: true
